FFWEB-1928: Added information about `default-query` requirements and implications
FACT-Finder-Web-Components/documentation pull request #282
Opened 2021-01-26 13:47 UTC by a-laurowski

2021-01-27 12:46 UTC, omikron-fp requested changes
Remarks apply to `4.x`, too.

2021-01-27 12:46 UTC, omikron-fp commented on markdown/3.x/en/api/ff-communication.api.md
> +| **search-immediate**&nbsp;(Boolean) | If this property is present, FACT-Finder Web Components will start searching as soon as they are loaded. For this to work, a `default-query` needs to be set wi
Placing the reference to `default-query` at the end might allow a smoother reading flow.
```suggestion
| **search-immediate**&nbsp;(Boolean) | If this property is present, FACT-Finder Web Components will start searching as soon as they are loaded. For this to work, a `default-query` needs to be set with a correct value or to be not set at all (see `default-query` description). |
```

2021-01-27 12:46 UTC, omikron-fp commented on markdown/3.x/en/api/ff-communication.api.md
> +| **default-query**&nbsp; (String) (default: '*') | Whenever a search is performed without a search query, this value will be used as default search term. This attribute will not accept empty or whit
```suggestion
| **default-query**&nbsp; (String) (default: '*') | Whenever a search is performed without a search query, this value will be used as default search term. This attribute will not accept empty or whitespace-only strings as its value. |
```

2021-01-27 14:31 UTC, a-laurowski commented on markdown/3.x/en/api/ff-communication.api.md
> +| **default-query**&nbsp; (String) (default: '*') | Whenever a search is performed without a search query, this value will be used as default search term. This attribute will not accept empty or whit
> Remarks apply to `4.x`, too.
applied

2021-01-28 06:57 UTC, omikron-fp approved these changes

2021-01-28 07:15 UTC, merged